#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

#(wmake libso BCs && wmake)
cd ./fluxSchemes
wclean
wmake
cd ..
wmake


# ----------------------------------------------------------------- end-of-file
